# Generated by Django 5.2.9 on 2026-02-03 06:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Axe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "type_axe",
                    models.CharField(
                        choices=[
                            ("RN", "Route Nationale"),
                            ("RR", "Route Régionale"),
                            ("RC", "Route Communale"),
                            ("AU", "Autre"),
                        ],
                        default="AU",
                        max_length=2,
                        verbose_name="Type d'axe",
                    ),
                ),
                (
                    "longueur_total",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Longueur Totale (km)",
                    ),
                ),
                (
                    "pko_lieu",
                    models.CharField(
                        default="", max_length=255, verbose_name="Lieu PK Début"
                    ),
                ),
                (
                    "pk_final_lieu",
                    models.CharField(
                        default="", max_length=255, verbose_name="Lieu PK Final"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description de l'axe"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attache_suivi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Attaché de suivi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Axe",
                "verbose_name_plural": "Axes",
            },
        ),
        migrations.CreateModel(
            name="Marche",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "num_marche",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="N° Marché"
                    ),
                ),
                (
                    "type_travaux",
                    models.CharField(
                        choices=[
                            ("ENTRETIEN_C", "Entretien Courant"),
                            ("ENTRETIEN_P", "Entretien Périodique"),
                            ("TRAITEMENT_PC", "Traitement de Points Critiques"),
                            ("REHABILITATION", "Réhabilitation / Reconstruction"),
                            ("TERRASSEMENT", "Terrassement"),
                            ("CHAUSSEE", "Chaussée / Revêtement"),
                            ("OUVRAGE_ART", "Ouvrages d'Art (Ponts/Dalots)"),
                            ("ASSAINISSEMENT", "Assainissement / Drainage"),
                            ("SIGNALISATION", "Signalisation et Sécurité"),
                            ("AUTRE", "Autre Type"),
                        ],
                        default="ENTRETIEN_C",
                        max_length=50,
                        verbose_name="Type de Travaux",
                    ),
                ),
                (
                    "categorie_oeuvre",
                    models.CharField(
                        choices=[("GROS", "Gros Œuvre"), ("PETIT", "Petit Œuvre")],
                        default="GROS",
                        max_length=10,
                        verbose_name="Catégorie d'Œuvre",
                    ),
                ),
                ("description", models.TextField(verbose_name="Objet")),
                ("resume", models.CharField(max_length=255, verbose_name="Résumé")),
                (
                    "financement",
                    models.CharField(
                        choices=[
                            ("RPI", "RPI"),
                            ("FIN_EX", "Financement Extérieur"),
                            ("FER", "FER"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=10,
                    ),
                ),
                (
                    "detail_financement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tiers", models.CharField(help_text="Ex: DAU, PDDR", max_length=100)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "titulaire",
                    models.CharField(
                        max_length=255, verbose_name="Entreprise Titulaire"
                    ),
                ),
                ("os_com", models.DateField(verbose_name="Date OS Commencement")),
                (
                    "delai_unit",
                    models.CharField(
                        choices=[
                            ("JOURS", "Jours"),
                            ("MOIS", "Mois"),
                            ("SEMAINE", "Semaine"),
                        ],
                        default="MOIS",
                        max_length=10,
                    ),
                ),
                ("delai_nombre", models.IntegerField(verbose_name="Nombre de délai")),
                (
                    "axe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marches",
                        to="travaux.axe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marché",
                "verbose_name_plural": "Marchés",
            },
        ),
        migrations.CreateModel(
            name="Avancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_avancement",
                    models.DateField(verbose_name="Date de l'état d'avancement"),
                ),
                (
                    "avancement_physique",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Avancement Physique (%)",
                    ),
                ),
                (
                    "avancement_financier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Avancement Financier (%)",
                    ),
                ),
                (
                    "situation_w",
                    models.CharField(
                        choices=[
                            ("ETUDE", "Phase d'étude"),
                            ("PASSATION", "Passation de marché"),
                            ("EN_COURS", "En cours"),
                            ("ACHEVE", "Achéve"),
                            ("RESILIE", "Résilié"),
                        ],
                        default="EN_COURS",
                        max_length=20,
                        verbose_name="Situation",
                    ),
                ),
                (
                    "detail_situation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Détail de la situation"
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observations / Faits marquants",
                    ),
                ),
                (
                    "marche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avancements",
                        to="travaux.marche",
                        verbose_name="Marché",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avancement",
                "verbose_name_plural": "Avancements",
                "ordering": ["-date_avancement"],
            },
        ),
        migrations.CreateModel(
            name="MediaAvancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="travaux/%Y/%m/%d/", verbose_name="Fichier / Photo"
                    ),
                ),
                (
                    "legende",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Légende / Description"
                    ),
                ),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "avancement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="travaux.avancement",
                        verbose_name="État d'avancement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média d'avancement",
                "verbose_name_plural": "Médias d'avancement",
            },
        ),
        migrations.CreateModel(
            name="PKMarche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pk_debut",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="PK Début"
                    ),
                ),
                (
                    "pk_fin",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="PK Fin"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description du tronçon",
                    ),
                ),
                (
                    "marche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments_pk",
                        to="travaux.marche",
                        verbose_name="Marché",
                    ),
                ),
            ],
            options={
                "verbose_name": "PK du Marché",
                "verbose_name_plural": "PK des Marchés",
                "ordering": ["marche", "pk_debut"],
            },
        ),
        migrations.CreateModel(
            name="PKDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=255)),
                (
                    "pk_debut",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="PK Début"
                    ),
                ),
                (
                    "pk_fin",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="PK Fin"
                    ),
                ),
                (
                    "axe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments_districts",
                        to="travaux.axe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Découpage District",
                "verbose_name_plural": "Découpage Districts",
                "unique_together": {("axe", "pk_debut")},
            },
        ),
    ]
