# Generated by Django 5.2.9 on 2026-02-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Localisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ANTANANARIVO", "Antananarivo"),
                            ("ANTSIRANANA", "Antsiranana"),
                            ("FIANARANTSOA", "Fianarantsoa"),
                            ("MAHAJANGA", "Mahajanga"),
                            ("TOAMASINA", "Toamasina"),
                            ("TOLIARA", "Toliara"),
                        ],
                        max_length=20,
                        verbose_name="Province",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("ANALAMANGA", "Analamanga"),
                            ("VAKINANKARATRA", "Vakinankaratra"),
                            ("ITASY", "Itasy"),
                            ("BONGOLAVA", "Bongolava"),
                            ("SAVA", "Sava"),
                            ("DIANA", "Diana"),
                            ("MATSIATRA_AMBONY", "Matsiatra Ambony"),
                            ("AMORON_I_MANIA", "Amoron'i Mania"),
                            ("VATOVAVY", "Vatovavy"),
                            ("FITOVINANY", "Fitovinany"),
                            ("IHOROMBE", "Ihorombe"),
                            ("ATSIMO_ATSINANANA", "Atsimo-Atsinanana"),
                            ("BOENY", "Boeny"),
                            ("SOFIA", "Sofia"),
                            ("BETSIBOKA", "Betsiboka"),
                            ("MELAKY", "Melaky"),
                            ("ATSINANANA", "Atsinanana"),
                            ("ALAOTRA_MANGORO", "Alaotra-Mangoro"),
                            ("ANALANJIROFO", "Analanjirofo"),
                            ("ATSIMO_ANDREFANA", "Atsimo-Andrefana"),
                            ("ANDROY", "Androy"),
                            ("ANOSY", "Anosy"),
                            ("MENABE", "Menabe"),
                        ],
                        max_length=30,
                        verbose_name="Région",
                    ),
                ),
                (
                    "district",
                    models.CharField(max_length=100, verbose_name="Nom du District"),
                ),
            ],
            options={
                "verbose_name": "Localisation (District)",
                "verbose_name_plural": "Localisations",
                "ordering": ["province", "region", "district"],
                "unique_together": {("district", "region")},
            },
        ),
    ]
