# Generated by Django 5.2.9 on 2026-02-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0002_localisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="axe",
            name="pk_final_lieu",
        ),
        migrations.RemoveField(
            model_name="axe",
            name="pko_lieu",
        ),
        migrations.AddField(
            model_name="axe",
            name="pk_debut_district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="axes_depart",
                to="travaux.localisation",
                verbose_name="District de début (PK 0)",
            ),
        ),
        migrations.AddField(
            model_name="axe",
            name="pk_fin_district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="axes_fin",
                to="travaux.localisation",
                verbose_name="District de fin (PK Final)",
            ),
        ),
        migrations.AddField(
            model_name="axe",
            name="pko_lieu_detail",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Lieu précis PK Début"
            ),
        ),
    ]
