# Generated by Django 5.2.9 on 2026-02-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0003_remove_axe_pk_final_lieu_remove_axe_pko_lieu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="axe",
            name="pko_lieu_detail",
        ),
    ]
