# Generated by Django 5.2.9 on 2026-02-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0005_alter_pkdistrict_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="num_marche",
            field=models.CharField(max_length=255, verbose_name="N° Marché"),
        ),
    ]
