# Generated by Django 5.2.9 on 2026-02-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0006_alter_marche_num_marche"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="montant",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
