# Generated by Django 5.2.9 on 2026-02-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0010_alter_avancement_options_alter_axe_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="financement",
            field=models.CharField(
                choices=[
                    ("RPI", "RPI"),
                    ("FIN_EX", "Financement Extérieur"),
                    ("FER", "FER"),
                    ("AUTRE", "Autre"),
                ],
                max_length=10,
            ),
        ),
    ]
