# Generated by Django 5.2.9 on 2026-03-16 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0019_os_delai_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annuaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("ANALAMANGA", "Analamanga"),
                            ("VAKINANKARATRA", "Vakinankaratra"),
                            ("ITASY", "Itasy"),
                            ("BONGOLAVA", "Bongolava"),
                            ("SAVA", "Sava"),
                            ("DIANA", "Diana"),
                            ("MATSIATRA_AMBONY", "Matsiatra Ambony"),
                            ("AMORON_I_MANIA", "Amoron'i Mania"),
                            ("VATOVAVY", "Vatovavy"),
                            ("FITOVINANY", "Fitovinany"),
                            ("IHOROMBE", "Ihorombe"),
                            ("ATSIMO_ATSINANANA", "Atsimo-Atsinanana"),
                            ("BOENY", "Boeny"),
                            ("SOFIA", "Sofia"),
                            ("BETSIBOKA", "Betsiboka"),
                            ("MELAKY", "Melaky"),
                            ("ATSINANANA", "Atsinanana"),
                            ("ALAOTRA_MANGORO", "Alaotra-Mangoro"),
                            ("ANALANJIROFO", "Analanjirofo"),
                            ("ATSIMO_ANDREFANA", "Atsimo-Andrefana"),
                            ("ANDROY", "Androy"),
                            ("ANOSY", "Anosy"),
                            ("MENABE", "Menabe"),
                        ],
                        max_length=100,
                    ),
                ),
                ("fonction", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="avancement",
            name="situation_w",
            field=models.CharField(
                choices=[
                    ("En_ph", "En phase Etude"),
                    ("En_passation", "En passation de marché"),
                    ("En_cours", "En Cours"),
                    ("Arrete", "En Arrêt"),
                    ("Acheve", "Achevé"),
                    ("Résilié", "Résilié"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="marche",
            name="financement",
            field=models.CharField(
                choices=[
                    ("RPI", "RPI"),
                    ("FIN_EX", "Fin Ex"),
                    ("FR", "FR"),
                    ("AUTRE", "Autre"),
                ],
                max_length=10,
            ),
        ),
    ]
