# Generated by Django 5.2.9 on 2026-03-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0021_annuaire_nom"),
    ]

    operations = [
        migrations.AddField(
            model_name="annuaire",
            name="telephone1",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="annuaire",
            name="whatsapp1",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
