# Generated by Django 5.2.9 on 2026-03-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0022_annuaire_telephone1_annuaire_whatsapp1"),
    ]

    operations = [
        migrations.AddField(
            model_name="marche",
            name="delai_jours",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Jours supplémentaires"
            ),
        ),
        migrations.AddField(
            model_name="os",
            name="delai_jours_supplementaire",
            field=models.IntegerField(
                default=0,
                help_text="Complément en jours si l'unité principale est en Mois",
                verbose_name="Jours additionnels",
            ),
        ),
    ]
