# Generated by Django 5.2.9 on 2026-03-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0023_marche_delai_jours_os_delai_jours_supplementaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("ANALAMANGA", "Analamanga"),
                            ("VAKINANKARATRA", "Vakinankaratra"),
                            ("ITASY", "Itasy"),
                            ("BONGOLAVA", "Bongolava"),
                            ("SAVA", "Sava"),
                            ("DIANA", "Diana"),
                            ("MATSIATRA_AMBONY", "Matsiatra Ambony"),
                            ("AMORON_I_MANIA", "Amoron'i Mania"),
                            ("VATOVAVY", "Vatovavy"),
                            ("FITOVINANY", "Fitovinany"),
                            ("IHOROMBE", "Ihorombe"),
                            ("ATSIMO_ATSINANANA", "Atsimo-Atsinanana"),
                            ("BOENY", "Boeny"),
                            ("SOFIA", "Sofia"),
                            ("BETSIBOKA", "Betsiboka"),
                            ("MELAKY", "Melaky"),
                            ("ATSINANANA", "Atsinanana"),
                            ("ALAOTRA_MANGORO", "Alaotra-Mangoro"),
                            ("ANALANJIROFO", "Analanjirofo"),
                            ("ATSIMO_ANDREFANA", "Atsimo-Andrefana"),
                            ("ANDROY", "Androy"),
                            ("ANOSY", "Anosy"),
                            ("MENABE", "Menabe"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "direction_resp",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Direction Responsable",
                    ),
                ),
                (
                    "lieu",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Lieu de traversée / Rivière",
                    ),
                ),
                (
                    "nbr",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Capacité / Nombre"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="bacs/photos/"),
                ),
                (
                    "chef_bac",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Responsable du Bac",
                    ),
                ),
                (
                    "etat_bac",
                    models.CharField(
                        choices=[
                            ("Fonctionnel", "En service"),
                            ("Panne", "En panne / Réparation"),
                            ("Arreté", "Hors service / Crues"),
                            ("Maintenance", "En maintenance"),
                        ],
                        default="Fonctionnel",
                        max_length=20,
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bac de traversée",
                "verbose_name_plural": "Bacs de traversée",
                "ordering": ["-date_update"],
            },
        ),
    ]
