# Generated by Django 5.2.9 on 2026-03-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0024_bac"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConventionProgramme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(max_length=255, verbose_name="Section / Tronçon"),
                ),
                (
                    "region",
                    models.CharField(
                        max_length=100, verbose_name="Région de l'intervention"
                    ),
                ),
                (
                    "annee",
                    models.PositiveIntegerField(
                        default=2026, verbose_name="Année budgétaire"
                    ),
                ),
                (
                    "pk_debut",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="PK Début"
                    ),
                ),
                (
                    "localite_deb",
                    models.CharField(max_length=255, verbose_name="Localité de début"),
                ),
                (
                    "pk_fin",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="PK Fin"
                    ),
                ),
                (
                    "localite_fin",
                    models.CharField(max_length=255, verbose_name="Localité de fin"),
                ),
                (
                    "longueur",
                    models.DecimalField(
                        decimal_places=3,
                        editable=False,
                        max_digits=10,
                        verbose_name="Longueur Totale (km)",
                    ),
                ),
                (
                    "longueur_traite",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Longueur effectivement traitée (km)",
                    ),
                ),
                (
                    "nature_surface",
                    models.CharField(
                        choices=[
                            ("RB", "Revêtement Bitumineux"),
                            ("RT", "Revêtement Terre"),
                        ],
                        default="RT",
                        max_length=2,
                    ),
                ),
                (
                    "montant_minima",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Montant Minima (Ar)",
                    ),
                ),
                (
                    "montant_souhaite",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Montant Souhaité (Ar)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "axe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conventions",
                        to="travaux.axe",
                        verbose_name="Axe Routier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convention Programme",
                "verbose_name_plural": "Conventions Programmes",
                "ordering": ["-annee", "axe__designation", "pk_debut"],
            },
        ),
    ]
