# Generated by Django 5.2.9 on 2026-03-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0025_conventionprogramme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conventionprogramme",
            name="region",
            field=models.CharField(
                choices=[
                    ("ANALAMANGA", "Analamanga"),
                    ("VAKINANKARATRA", "Vakinankaratra"),
                    ("ITASY", "Itasy"),
                    ("BONGOLAVA", "Bongolava"),
                    ("SAVA", "Sava"),
                    ("DIANA", "Diana"),
                    ("MATSIATRA_AMBONY", "Matsiatra Ambony"),
                    ("AMORON_I_MANIA", "Amoron'i Mania"),
                    ("VATOVAVY", "Vatovavy"),
                    ("FITOVINANY", "Fitovinany"),
                    ("IHOROMBE", "Ihorombe"),
                    ("ATSIMO_ATSINANANA", "Atsimo-Atsinanana"),
                    ("BOENY", "Boeny"),
                    ("SOFIA", "Sofia"),
                    ("BETSIBOKA", "Betsiboka"),
                    ("MELAKY", "Melaky"),
                    ("ATSINANANA", "Atsinanana"),
                    ("ALAOTRA_MANGORO", "Alaotra-Mangoro"),
                    ("ANALANJIROFO", "Analanjirofo"),
                    ("ATSIMO_ANDREFANA", "Atsimo-Andrefana"),
                    ("ANDROY", "Androy"),
                    ("ANOSY", "Anosy"),
                    ("MENABE", "Menabe"),
                ],
                max_length=100,
                verbose_name="Région de l'intervention",
            ),
        ),
    ]
