# Generated by Django 5.2.9 on 2026-03-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0027_alter_bac_options_remove_bac_direction_resp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bac",
            name="besoin_entretien_bac",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=20,
                null=True,
                verbose_name="Besoin Financement (Ar)",
            ),
        ),
    ]
