# Generated by Django 5.2.9 on 2026-03-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0028_alter_bac_besoin_entretien_bac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bac",
            name="nbre_passeur_ar",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Passeurs AR"
            ),
        ),
        migrations.AlterField(
            model_name="bac",
            name="nbre_passeur_ecd",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Passeurs ECD"
            ),
        ),
        migrations.AlterField(
            model_name="bac",
            name="nbre_passeur_fonc",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Passeurs Fonctionnaires"
            ),
        ),
    ]
