# Generated by Django 5.2.9 on 2026-03-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "travaux",
            "0029_alter_bac_nbre_passeur_ar_alter_bac_nbre_passeur_ecd_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marche",
            name="categorie_oeuvre",
        ),
        migrations.RemoveField(
            model_name="marche",
            name="type_travaux",
        ),
    ]
