# Generated by Django 5.2.9 on 2026-03-30 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0030_remove_marche_categorie_oeuvre_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravauxGlisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auc",
                    models.CharField(
                        blank=True,
                        choices=[("En attente", "En Attente"), ("Obtenue", "Obtenue")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_auc", models.DateField(blank=True, null=True)),
                (
                    "passation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en_cours", "Passation en cours"),
                            ("OS_delivre", "OS Délivré"),
                            ("Lancement_AO_cours", "Lancement AO En cours"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "annee_origine",
                    models.PositiveIntegerField(
                        default=2025, verbose_name="Année d'origine"
                    ),
                ),
                (
                    "annee_report",
                    models.PositiveIntegerField(
                        default=2026, verbose_name="Reporté en"
                    ),
                ),
                (
                    "axe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travaux_glisses",
                        to="travaux.axe",
                        verbose_name="Axe Routier",
                    ),
                ),
                (
                    "marche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glissements",
                        to="travaux.marche",
                    ),
                ),
            ],
        ),
    ]
