# Generated by Django 5.2.9 on 2026-04-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0032_travauxglisse_montant_reliquat"),
    ]

    operations = [
        migrations.AddField(
            model_name="marche",
            name="est_anticipe",
            field=models.BooleanField(
                default=False,
                help_text="Cocher si la procédure est lancée de manière anticipée",
                verbose_name="Marché Anticipé",
            ),
        ),
        migrations.AddField(
            model_name="marche",
            name="etape_actuelle",
            field=models.CharField(
                choices=[
                    ("ETUDE", "En cours d'Étude / Montage APD"),
                    ("VISE_TECH", "Dossier Visé (Technique)"),
                    ("TEF", "Transmis pour Examen Financier (TEF)"),
                    ("AO_LANCE", "Appel d'Offres Lancé"),
                    ("EVALUATION", "En cours d'Évaluation / Attribution"),
                    ("SIGNATURE", "En cours de Signature / Approbation"),
                    ("ATTRIBUE", "Attribué (En attente OS)"),
                    ("EXE", "En cours d'Exécution (OS délivré)"),
                ],
                default="ETUDE",
                max_length=20,
            ),
        ),
    ]
