# Generated by Django 5.2.9 on 2026-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0038_pkdistrict_deb_pkdistrict_fin_pkdistrict_longueur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="responsable",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DINFRA", "DINFRA"),
                    ("DER", "DER"),
                    ("DAU", "DAU"),
                    ("CCP", "CPP"),
                ],
                max_length=10,
                null=True,
                verbose_name="Institution Responsable",
            ),
        ),
    ]
