# Generated by Django 5.2.9 on 2026-06-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0039_alter_marche_responsable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="responsable",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AR", "AR"),
                    ("CCP", "CCP"),
                    ("DAU", "DAU"),
                    ("DER", "DER"),
                    ("DINFRA", "DINFRA"),
                    ("PACFC", "PACFC"),
                    ("PCMCI", "PCMCI"),
                    ("PDDR", "PDDR"),
                ],
                max_length=10,
                null=True,
                verbose_name="Institution Responsable",
            ),
        ),
    ]
