# Generated by Django 5.2.9 on 2026-09-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travaux', '0041_add_marche_region'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pkmarche',
            name='unique_pk_debut_par_marche',
        ),
    ]
