# Generated by Django 5.2.9 on 2026-09-22 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travaux', '0042_remove_pkmarche_unique_pk_debut_par_marche'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_marche', to=settings.AUTH_USER_MODEL)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='travaux.marche')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['marche', 'created_at'], name='travaux_mes_marche__5d8baa_idx')],
            },
        ),
    ]
