# Generated by Django 5.2.9 on 2026-09-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travaux', '0043_messagemarche'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemarche',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='travaux/discussions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='messagemarche',
            name='contenu',
            field=models.TextField(blank=True, default=''),
        ),
    ]
