# Generated by Django 5.2.9 on 2026-02-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0004_remove_axe_pko_lieu_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pkdistrict",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segments_traverses",
                to="travaux.localisation",
                verbose_name="District traversé",
            ),
        ),
    ]
