# Generated by Django 5.2.9 on 2026-02-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0007_alter_marche_montant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="os_com",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date OS Commencement"
            ),
        ),
    ]
