# Generated by Django 5.2.9 on 2026-02-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0008_alter_marche_os_com"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="delai_nombre",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Nombre de délai"
            ),
        ),
    ]
