# Generated by Django 5.2.9 on 2026-02-11 06:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0009_alter_marche_delai_nombre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avancement",
            options={"ordering": ["-date_avancement"]},
        ),
        migrations.AlterModelOptions(
            name="axe",
            options={},
        ),
        migrations.AlterModelOptions(
            name="marche",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mediaavancement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pkdistrict",
            options={"ordering": ["axe", "pk_debut"]},
        ),
        migrations.AlterUniqueTogether(
            name="localisation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="pkdistrict",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="avancement",
            name="avancement_financier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="avancement",
            name="avancement_physique",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="avancement",
            name="date_avancement",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="avancement",
            name="detail_situation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avancement",
            name="marche",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avancements",
                to="travaux.marche",
            ),
        ),
        migrations.AlterField(
            model_name="avancement",
            name="observation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avancement",
            name="situation_w",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="axe",
            name="attache_suivi",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="axe",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="axe",
            name="designation",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="axe",
            name="longueur_total",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="axe",
            name="pk_debut_district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="axes_depart",
                to="travaux.localisation",
            ),
        ),
        migrations.AlterField(
            model_name="axe",
            name="pk_fin_district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="axes_fin",
                to="travaux.localisation",
            ),
        ),
        migrations.AlterField(
            model_name="axe",
            name="type_axe",
            field=models.CharField(
                choices=[
                    ("RN", "Route Nationale"),
                    ("RR", "Route Régionale"),
                    ("RC", "Route Communale"),
                    ("AU", "Autre"),
                ],
                default="AU",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="localisation",
            name="district",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="localisation",
            name="province",
            field=models.CharField(
                choices=[
                    ("ANTANANARIVO", "Antananarivo"),
                    ("ANTSIRANANA", "Antsiranana"),
                    ("FIANARANTSOA", "Fianarantsoa"),
                    ("MAHAJANGA", "Mahajanga"),
                    ("TOAMASINA", "Toamasina"),
                    ("TOLIARA", "Toliara"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="localisation",
            name="region",
            field=models.CharField(
                choices=[
                    ("ANALAMANGA", "Analamanga"),
                    ("VAKINANKARATRA", "Vakinankaratra"),
                    ("ITASY", "Itasy"),
                    ("BONGOLAVA", "Bongolava"),
                    ("SAVA", "Sava"),
                    ("DIANA", "Diana"),
                    ("MATSIATRA_AMBONY", "Matsiatra Ambony"),
                    ("AMORON_I_MANIA", "Amoron'i Mania"),
                    ("VATOVAVY", "Vatovavy"),
                    ("FITOVINANY", "Fitovinany"),
                    ("IHOROMBE", "Ihorombe"),
                    ("ATSIMO_ATSINANANA", "Atsimo-Atsinanana"),
                    ("BOENY", "Boeny"),
                    ("SOFIA", "Sofia"),
                    ("BETSIBOKA", "Betsiboka"),
                    ("MELAKY", "Melaky"),
                    ("ATSINANANA", "Atsinanana"),
                    ("ALAOTRA_MANGORO", "Alaotra-Mangoro"),
                    ("ANALANJIROFO", "Analanjirofo"),
                    ("ATSIMO_ANDREFANA", "Atsimo-Andrefana"),
                    ("ANDROY", "Androy"),
                    ("ANOSY", "Anosy"),
                    ("MENABE", "Menabe"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="marche",
            name="categorie_oeuvre",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="marche",
            name="delai_nombre",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marche",
            name="delai_unit",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="marche",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="marche",
            name="financement",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="marche",
            name="num_marche",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="marche",
            name="os_com",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marche",
            name="resume",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="marche",
            name="tiers",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="marche",
            name="titulaire",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="marche",
            name="type_travaux",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="mediaavancement",
            name="avancement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="travaux.avancement",
            ),
        ),
        migrations.AlterField(
            model_name="mediaavancement",
            name="fichier",
            field=models.FileField(upload_to="travaux/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="mediaavancement",
            name="legende",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pkdistrict",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segments_traverses",
                to="travaux.localisation",
            ),
        ),
        migrations.AlterField(
            model_name="pkdistrict",
            name="pk_debut",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pkdistrict",
            name="pk_fin",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AddIndex(
            model_name="avancement",
            index=models.Index(
                fields=["date_avancement"], name="travaux_ava_date_av_8db63b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="localisation",
            constraint=models.UniqueConstraint(
                fields=("district", "region"), name="unique_district_region"
            ),
        ),
        migrations.AddConstraint(
            model_name="pkdistrict",
            constraint=models.UniqueConstraint(
                fields=("axe", "pk_debut"), name="unique_pk_debut_par_axe"
            ),
        ),
        migrations.AddConstraint(
            model_name="pkmarche",
            constraint=models.UniqueConstraint(
                fields=("marche", "pk_debut"), name="unique_pk_debut_par_marche"
            ),
        ),
    ]
