# Generated by Django 5.2.9 on 2026-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0011_alter_marche_financement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="financement",
            field=models.CharField(
                choices=[
                    ("RPI", "RPI"),
                    ("FIN_EX", "Financement Extérieur"),
                    ("FR", "FR"),
                    ("FER", "FER"),
                    ("AUTRE", "Autre"),
                ],
                max_length=10,
            ),
        ),
    ]
