# Generated by Django 5.2.9 on 2026-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0013_alter_avancement_situation_w"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avancement",
            name="situation_w",
            field=models.CharField(
                choices=[
                    ("En_ph", "En phase Etude"),
                    ("En_passation", "En passation de marché"),
                    ("En_cours", "En Cours"),
                    ("Acheve", "Achevé"),
                    ("Résilié", "Résilié"),
                ],
                max_length=20,
            ),
        ),
    ]
