# Generated by Django 5.2.9 on 2026-02-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0014_alter_avancement_situation_w"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="num_marche",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
