# Generated by Django 5.2.9 on 2026-02-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0015_alter_marche_num_marche"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="delai_unit",
            field=models.CharField(
                choices=[
                    ("JOUR", "Jour(s)"),
                    ("SEMAINE", "Semaine(s)"),
                    ("MOIS", "Mois"),
                ],
                default="MOIS",
                max_length=10,
            ),
        ),
    ]
