# Generated by Django 5.2.9 on 2026-03-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0016_alter_marche_delai_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="financement",
            field=models.CharField(
                choices=[
                    ("RPI", "RPI"),
                    ("FIN_EX", "Financement Extérieur"),
                    ("FR", "FR"),
                    ("AUTRE", "Autre"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_os",
                    models.CharField(
                        choices=[
                            ("COMMENCEMENT", "OS de Commencement"),
                            ("ARRET", "OS d'Arrêt"),
                            ("REPRISE", "OS de Reprise"),
                            ("AVENANT_DELAI", "Avenant de Délai"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_os", models.DateField()),
                (
                    "delai_supplementaire",
                    models.IntegerField(
                        default=0, help_text="Valeur à ajouter au délai initial"
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "marche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordres_service",
                        to="travaux.marche",
                    ),
                ),
                (
                    "os_arret_concerne",
                    models.OneToOneField(
                        blank=True,
                        help_text="Si c'est une reprise, quel arrêt prend fin ?",
                        limit_choices_to={"type_os": "ARRET"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="os_reprise",
                        to="travaux.os",
                    ),
                ),
            ],
            options={
                "ordering": ["date_os"],
            },
        ),
    ]
