# Generated by Django 5.2.9 on 2026-03-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0017_alter_marche_financement_os"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avancement",
            name="situation_w",
            field=models.CharField(
                choices=[
                    ("En_ph", "En phase Etude"),
                    ("En_passation", "En passation de marché"),
                    ("En_cours", "En Cours"),
                    ("Arrete", "Arrêté"),
                    ("Acheve", "Achevé"),
                    ("Résilié", "Résilié"),
                ],
                max_length=20,
            ),
        ),
    ]
