# Generated by Django 5.2.9 on 2026-03-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0018_alter_avancement_situation_w"),
    ]

    operations = [
        migrations.AddField(
            model_name="os",
            name="delai_unit",
            field=models.CharField(
                choices=[
                    ("JOUR", "Jour(s)"),
                    ("SEMAINE", "Semaine(s)"),
                    ("MOIS", "Mois"),
                ],
                default="MOIS",
                max_length=10,
            ),
        ),
    ]
