# Generated by Django 5.2.9 on 2026-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0020_annuaire_alter_avancement_situation_w_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annuaire",
            name="nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
