# Generated by Django 5.2.9 on 2026-03-27 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0026_alter_conventionprogramme_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bac",
            options={
                "ordering": ["region", "axe", "pk_bac"],
                "verbose_name": "Bac de traversée",
                "verbose_name_plural": "Bacs de traversée",
            },
        ),
        migrations.RemoveField(
            model_name="bac",
            name="direction_resp",
        ),
        migrations.RemoveField(
            model_name="bac",
            name="lieu",
        ),
        migrations.RemoveField(
            model_name="bac",
            name="nbr",
        ),
        migrations.AddField(
            model_name="bac",
            name="annee_acquisition",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Année d'acquisition"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="annee_entretien",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Année dernier entretien"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="annee_exercice",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Année d'exercice"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="axe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bacs",
                to="travaux.axe",
                verbose_name="Axe Routier",
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="besoin_entretien_bac",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                verbose_name="Besoin Financement (Ar)",
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="constructeur",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Constructeur"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="detail_etat_bac",
            field=models.TextField(
                blank=True, null=True, verbose_name="Détails sur l'état"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="employeur_passeur",
            field=models.CharField(
                blank=True,
                choices=[("DRTP", "DRTP"), ("AR", "AR"), ("DRTP/AR", "DRTP/AR")],
                max_length=20,
                null=True,
                verbose_name="Employeurs des passeurs",
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="etat_financement_bac",
            field=models.CharField(
                blank=True,
                choices=[("ACQUIS", "ACQUIS"), ("A RECHERCHER", "A RECHERCHER")],
                max_length=20,
                null=True,
                verbose_name="Statut Financement",
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="gestionnaire",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Gestionnaire Actuel",
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=10,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="localite",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Localité"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=10,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="longueur_travers",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Longueur du Traversé (ml)"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="nbr_capacite",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Capacité (Pers/Véhicules)"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="nbre_passeur_ar",
            field=models.PositiveIntegerField(default=0, verbose_name="Passeurs AR"),
        ),
        migrations.AddField(
            model_name="bac",
            name="nbre_passeur_ecd",
            field=models.PositiveIntegerField(default=0, verbose_name="Passeurs ECD"),
        ),
        migrations.AddField(
            model_name="bac",
            name="nbre_passeur_fonc",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Passeurs Fonctionnaires"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="observation",
            field=models.TextField(blank=True, null=True, verbose_name="Observations"),
        ),
        migrations.AddField(
            model_name="bac",
            name="pk_bac",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="PK",
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="portance",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Portance (Tonnes)"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="projet_en_cours",
            field=models.TextField(
                blank=True, null=True, verbose_name="Projet en cours"
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="projet_en_perspective",
            field=models.TextField(blank=True, null=True, verbose_name="Projet en vue"),
        ),
        migrations.AddField(
            model_name="bac",
            name="propulsion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Moteur", "Moteur"),
                    ("Perche", "Perche"),
                    ("Treuil", "Treuil"),
                    ("Treuil_a_moteur", "Treuil à moteur"),
                ],
                max_length=50,
                null=True,
                verbose_name="Propulsion",
            ),
        ),
        migrations.AddField(
            model_name="bac",
            name="riviere",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Rivière / Franchissement",
            ),
        ),
        migrations.AlterField(
            model_name="bac",
            name="etat_bac",
            field=models.CharField(
                choices=[
                    ("Operationel", "Opérationnel"),
                    ("En maintenance", "En Maintenance"),
                    ("Fonctionnel_degrade", "Fonctionnel avec dégradation"),
                    ("degrade", "Dégradé"),
                    ("Hors_usage", "Hors d'usage"),
                ],
                default="Operationel",
                max_length=50,
                verbose_name="État du Bac",
            ),
        ),
        migrations.AlterField(
            model_name="bac",
            name="region",
            field=models.CharField(
                choices=[
                    ("ANALAMANGA", "Analamanga"),
                    ("VAKINANKARATRA", "Vakinankaratra"),
                    ("ITASY", "Itasy"),
                    ("BONGOLAVA", "Bongolava"),
                    ("SAVA", "Sava"),
                    ("DIANA", "Diana"),
                    ("MATSIATRA_AMBONY", "Matsiatra Ambony"),
                    ("AMORON_I_MANIA", "Amoron'i Mania"),
                    ("VATOVAVY", "Vatovavy"),
                    ("FITOVINANY", "Fitovinany"),
                    ("IHOROMBE", "Ihorombe"),
                    ("ATSIMO_ATSINANANA", "Atsimo-Atsinanana"),
                    ("BOENY", "Boeny"),
                    ("SOFIA", "Sofia"),
                    ("BETSIBOKA", "Betsiboka"),
                    ("MELAKY", "Melaky"),
                    ("ATSINANANA", "Atsinanana"),
                    ("ALAOTRA_MANGORO", "Alaotra-Mangoro"),
                    ("ANALANJIROFO", "Analanjirofo"),
                    ("ATSIMO_ANDREFANA", "Atsimo-Andrefana"),
                    ("ANDROY", "Androy"),
                    ("ANOSY", "Anosy"),
                    ("MENABE", "Menabe"),
                ],
                max_length=100,
                verbose_name="Région",
            ),
        ),
    ]
