# Generated by Django 5.2.9 on 2026-03-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0031_travauxglisse"),
    ]

    operations = [
        migrations.AddField(
            model_name="travauxglisse",
            name="montant_reliquat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
