# Generated by Django 5.2.9 on 2026-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0033_marche_est_anticipe_marche_etape_actuelle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avancement",
            name="situation_w",
            field=models.CharField(
                choices=[
                    ("En_cours", "En Cours"),
                    ("Arrete", "En Arrêt"),
                    ("Acheve", "Achevé"),
                    ("Résilié", "Résilié"),
                ],
                max_length=20,
            ),
        ),
    ]
