# Generated by Django 5.2.9 on 2026-04-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0034_alter_avancement_situation_w"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marche",
            name="financement",
            field=models.CharField(
                choices=[
                    ("Rech_finan", "Recherche Financement"),
                    ("RPI", "RPI"),
                    ("FIN_EX", "Fin Ex"),
                    ("FR", "FR"),
                    ("AUTRE", "Autre"),
                ],
                max_length=10,
            ),
        ),
    ]
