# Generated by Django 5.2.9 on 2026-04-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0035_alter_marche_financement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="axe",
            name="type_axe",
            field=models.CharField(
                choices=[
                    ("RN", "Route Nationale"),
                    ("RR", "Route Régionale"),
                    ("RC", "Route Communale"),
                    ("AU", "Autre"),
                    ("FL", "FLY OVER"),
                ],
                default="AU",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="marche",
            name="etape_actuelle",
            field=models.CharField(
                choices=[
                    ("ETUDE", "En cours d'Étude / Montage APD"),
                    ("VISE_TECH", "Dossier Visé (Technique)"),
                    ("PASSATION", "EN PASSATION DU MARCHE"),
                    ("TEF", "Transmis pour Examen Financier (TEF)"),
                    ("AO_LANCE", "Appel d'Offres Lancé"),
                    ("EVALUATION", "En cours d'Évaluation / Attribution"),
                    ("SIGNATURE", "En cours de Signature / Approbation"),
                    ("ATTRIBUE", "Attribué (En attente OS)"),
                    ("EXE", "En cours d'Exécution (OS délivré)"),
                ],
                default="EXE",
                max_length=20,
            ),
        ),
    ]
