# Generated by Django 5.2.9 on 2026-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0036_alter_axe_type_axe_alter_marche_etape_actuelle"),
    ]

    operations = [
        migrations.AddField(
            model_name="marche",
            name="categorie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PONT", "PONT"),
                    ("BACS", "BACS"),
                    ("VR_DI", "VOIES URBAINES ET DES DISTRICTS"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marche",
            name="responsable",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DINFRA", "DINFRA"),
                    ("DER", "DER"),
                    ("DAU", "DAU"),
                    ("CCP", "CPP"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="axe",
            name="type_axe",
            field=models.CharField(
                choices=[
                    ("RN", "Route Nationale"),
                    ("RR", "Route Régionale"),
                    ("RC", "Route Communale"),
                    ("AU", "Autre"),
                    ("FL", "FLY OVER"),
                    ("PT", "PONT"),
                ],
                default="AU",
                max_length=2,
            ),
        ),
    ]
