# Generated by Django 5.2.9 on 2026-05-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0037_marche_categorie_marche_responsable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pkdistrict",
            name="deb",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Lieu Debut"
            ),
        ),
        migrations.AddField(
            model_name="pkdistrict",
            name="fin",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Lieu Fin"
            ),
        ),
        migrations.AddField(
            model_name="pkdistrict",
            name="longueur",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                editable=False,
                max_digits=10,
                verbose_name="Longueur Totale (km)",
            ),
        ),
        migrations.AddField(
            model_name="pkdistrict",
            name="section",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SECTION"
            ),
        ),
        migrations.AddField(
            model_name="pkdistrict",
            name="surface",
            field=models.CharField(
                blank=True, choices=[("RB", "RB"), ("RT", "RT")], null=True
            ),
        ),
    ]
