# Generated by assistant: add region field to Marche
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travaux", "0040_alter_marche_responsable"),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='region',
            field=models.CharField(max_length=64, blank=True, null=True),
        ),
    ]
