# Generated by Django 5.2.9 on 2026-04-17 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("travaux", "0036_alter_axe_type_axe_alter_marche_etape_actuelle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doleance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "lieu",
                    models.CharField(
                        blank=True, null=True, verbose_name="LIEU DE RECUEIL"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "type_autorite",
                    models.CharField(
                        choices=[
                            ("depute", "DEPUTE"),
                            ("cr", "CHEF DE REGION"),
                            ("maire", "MAIRE"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "auteur",
                    models.CharField(
                        max_length=255, verbose_name="Auteur de la demande"
                    ),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours de traitement"),
                            ("traite", "Traité"),
                            ("classe", "Classé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "piece_jointe",
                    models.FileField(blank=True, null=True, upload_to="doleances/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts_doleances",
                        to="travaux.localisation",
                    ),
                ),
                (
                    "responsable_insert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Intervenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("fonction", models.CharField(blank=True, max_length=255, null=True)),
                ("service", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EtapeTraitement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("est_terminee", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doleance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="apitp.doleance",
                    ),
                ),
                (
                    "effectue_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervenants_Dol",
                        to="apitp.intervenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="doleances/")),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "doleance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="apitp.doleance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lieu", models.CharField(blank=True, null=True, verbose_name="LIEU")),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "type_promesse",
                    models.CharField(
                        choices=[
                            ("presidentielle", "Présidentielle"),
                            ("parlementaire", "Parlementaire"),
                            ("ministerielle", "Ministérielle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_annonce", models.DateField()),
                ("date_prevue", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("non_demarre", "Non démarré"),
                            ("en_cours", "En cours"),
                            ("realise", "Réalisé"),
                            ("retard", "En retard"),
                            ("abandonne", "Abandonné"),
                        ],
                        default="non_demarre",
                        max_length=20,
                    ),
                ),
                ("taux_realisation", models.FloatField(default=0)),
                (
                    "localisation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("observation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts_promesse",
                        to="travaux.localisation",
                    ),
                ),
                (
                    "responsableInser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EtapePromesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("progression", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "effectue_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervenants_Prom",
                        to="apitp.intervenant",
                    ),
                ),
                (
                    "promesse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="apitp.promesse",
                    ),
                ),
            ],
        ),
    ]
