# Generated by Django 5.2.9 on 2026-02-03 06:36

import django.db.models.deletion
import om.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectionTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("DENOMINATION", models.CharField(max_length=100)),
                ("SIGLE", models.CharField(max_length=20)),
                (
                    "hierarchie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sous_directions",
                        to="om.directiontp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_depart", models.DateField()),
                ("date_arrivee", models.DateField()),
                ("Motif", models.TextField()),
                ("lieu", models.CharField(default="", max_length=250)),
                ("use_vehicle_administratif", models.BooleanField(default=True)),
                (
                    "direction_rattache",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_vehicule",
                        to="om.directiontp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personneltp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "IM",
                    models.IntegerField(
                        default=om.models.generate_immatricule, unique=True
                    ),
                ),
                ("Nom_prenom", models.CharField(max_length=250)),
                ("Fonction", models.CharField(max_length=250)),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnels",
                        to="om.directiontp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Missionnaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fonction_mission",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "Mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missionnaires",
                        to="om.mission",
                    ),
                ),
                (
                    "IM",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="om.personneltp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompteAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default="profiles/images/default.png",
                        null=True,
                        upload_to="profiles/images/",
                    ),
                ),
                (
                    "peut_saisir_donnees",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si cet utilisateur est autorisé à créer ou modifier des missions.",
                        verbose_name="Peut saisir des données/missions",
                    ),
                ),
                (
                    "est_gestionnaire_mission",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si cet agent a les droits de créer et valider des missions.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur Django",
                    ),
                ),
                (
                    "personnel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compte_agent",
                        to="om.personneltp",
                        verbose_name="Informations Personnel TP",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Matricule", models.CharField(max_length=50)),
                ("marque", models.CharField(max_length=100)),
                (
                    "direction_rattache",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="om.directiontp",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mission",
            name="vehicule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="om.vehicle",
            ),
        ),
    ]
