# Generated by Django 5.2.9 on 2026-02-12 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("om", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="Matricule",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="elements_a_reparer",
            field=models.TextField(
                blank=True, help_text="Listez les pièces ou problèmes ici", null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="etat_technique",
            field=models.CharField(
                choices=[
                    ("Bon", "Bon état"),
                    ("Moyen", "À surveiller"),
                    ("Mauvais", "Réparation nécessaire"),
                ],
                default="Bon",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="VehicleStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        choices=[
                            ("En_mission", "En Mission"),
                            ("Au_garage", "Garage"),
                            ("Parking", "Au Parking / Disponible"),
                            ("Autre", "Autre"),
                        ],
                        default="Parking",
                        max_length=20,
                    ),
                ),
                (
                    "emplacement_actuel",
                    models.CharField(
                        help_text="Ville, garage spécifique ou bureau", max_length=255
                    ),
                ),
                (
                    "missionnaire",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("observation", models.TextField(blank=True, null=True)),
                ("date_maj", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="om.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi de véhicule",
                "ordering": ["-date_maj"],
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="matricule",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
