# Generated by Django 5.2.9 on 2026-04-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apitp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doleance",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="doleance",
            name="date_mise_a_jour",
        ),
        migrations.RemoveField(
            model_name="doleance",
            name="date_soumission",
        ),
        migrations.RemoveField(
            model_name="doleance",
            name="lieu",
        ),
        migrations.RemoveField(
            model_name="doleance",
            name="piece_jointe",
        ),
        migrations.RemoveField(
            model_name="promesse",
            name="created_by",
        ),
        migrations.AddField(
            model_name="doleance",
            name="Origin",
            field=models.CharField(
                blank=True, null=True, verbose_name="En provenance De : "
            ),
        ),
        migrations.AddField(
            model_name="doleance",
            name="date_obtention",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
