# Generated by Django 5.2.9 on 2026-04-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apitp", "0002_remove_doleance_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promesse",
            name="localisation",
        ),
    ]
