# Generated by Django 5.2.9 on 2026-04-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apitp", "0003_remove_promesse_localisation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doleance",
            old_name="Origin",
            new_name="origin",
        ),
        migrations.RenameField(
            model_name="promesse",
            old_name="responsableInser",
            new_name="responsable_insert",
        ),
    ]
