# Generated by Django 5.2.9 on 2026-06-18 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BlocageAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debut", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                ("motif", models.CharField(max_length=255)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemandeAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("nom_demandeur", models.CharField(max_length=255)),
                ("organisme", models.CharField(blank=True, max_length=255)),
                ("fonction", models.CharField(blank=True, max_length=255)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("adresse", models.TextField(blank=True)),
                ("objet", models.TextField()),
                ("date_souhaitee", models.DateField(blank=True, null=True)),
                ("heure_souhaitee", models.TimeField(blank=True, null=True)),
                ("date_audience", models.DateTimeField(blank=True, null=True)),
                ("date_fin_audience", models.DateTimeField(blank=True, null=True)),
                ("observation_audience", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("RECU", "Reçu"),
                            ("EN_ETUDE", "En étude"),
                            ("PROGRAMME", "Programmé"),
                            ("ACCEPTE", "Accepté"),
                            ("REPORTE", "Reporté"),
                            ("STANDBY", "Stand By"),
                            ("REDIRIGE", "Redirigé"),
                            ("REFUSE", "Refusé"),
                            ("TRAITE", "Traité"),
                        ],
                        default="RECU",
                        max_length=20,
                    ),
                ),
                ("motif_redirection", models.TextField(blank=True)),
                ("date_redirection", models.DateTimeField(blank=True, null=True)),
                ("motif_refus", models.TextField(blank=True)),
                ("date_refus", models.DateTimeField(blank=True, null=True)),
                ("motif_standby", models.TextField(blank=True)),
                ("date_standby", models.DateTimeField(blank=True, null=True)),
                ("date_reception", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_traitees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "direction_redirigee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="audience.direction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'audience",
                "verbose_name_plural": "Demandes d'audience",
                "ordering": ["-date_reception"],
            },
        ),
        migrations.CreateModel(
            name="Historique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=255)),
                ("objet", models.CharField(max_length=255)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="audiences/")),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="audience.demandeaudience",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ancienne_date", models.DateTimeField()),
                ("nouvelle_date", models.DateTimeField()),
                ("motif", models.TextField()),
                ("date_report", models.DateTimeField(auto_now_add=True)),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="audience.demandeaudience",
                    ),
                ),
                (
                    "reporte_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
